# App
spring.application.name=makemytrip
server.port=8080

# MySQL Database
spring.datasource.url=mysql://root:NvmWsCTquyqZOgYcOHrJYkCaiMDaMIYG@yamanote.proxy.rlwy.net:19404/railway
spring.datasource.username=root
spring.datasource.password=NvmWsCTquyqZOgYcOHrJYkCaiMDaMIYG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Gemini API (get free key from https://aistudio.google.com)
gemini.api.key=AIzaSyBIbvBPG5H3mctX7NFAlnz6XxRU8ONK-ec
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# Gmail SMTP (use your Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=babishariyaz@gmail.com
spring.mail.password=zqcdhxjywcsnsvzw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App email settings
app.mail.from=babishariyaz@gmail.com
app.name=MakeMyTrip Clone

# Logging
logging.level.com.makemytrip=DEBUG
